# Generated by Django 4.1.3 on 2022-11-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0003_alter_media_description_alter_media_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
