# Generated by Django 4.1.3 on 2022-11-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0004_media_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='url',
        ),
    ]
