# Generated by Django 4.1.3 on 2022-11-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0005_remove_platform_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'get_latest_by': 'created_date', 'ordering': ('-created_date',)},
        ),
        migrations.AlterField(
            model_name='media',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medialib.creator'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
