# Generated by Django 4.1.3 on 2022-11-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0007_alter_media_title_alter_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
