# Generated by Django 4.1.3 on 2022-11-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0008_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
