# Generated by Django 4.1.3 on 2022-11-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0011_remove_media_source_media_source_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='reference',
            new_name='description',
        ),
        migrations.AddField(
            model_name='creator',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
