# Generated by Django 4.1.3 on 2022-12-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0014_externallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
