# Generated by Django 4.1.3 on 2022-12-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0015_externallink_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='bootstrap_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
