# Generated by Django 4.1.3 on 2022-12-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0017_date_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'get_latest_by': 'date', 'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='media',
            name='date_type',
            field=models.CharField(choices=[('C', 'Created date'), ('E', 'Created date estimate'), ('U', 'Uploaded date')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='date',
            field=models.DateField(default='1988-04-29'),
            preserve_default=False,
        ),
    ]
