# Generated by Django 4.1.3 on 2022-12-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0018_alter_media_options_media_date_type_alter_media_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='url',
            field=models.URLField(blank=True, max_length=400, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='url',
            field=models.URLField(max_length=400, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='media',
            name='source_url',
            field=models.URLField(blank=True, max_length=400, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(max_length=400, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='url',
            field=models.URLField(blank=True, max_length=400, verbose_name='URL'),
        ),
    ]
