# Generated by Django 4.1.3 on 2022-12-15 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0020_auto_20221215_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CC', 'Creative Commons License'), ('OT', 'Others')], max_length=2)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='uploaded time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
        ),
        migrations.RemoveField(
            model_name='media',
            name='date_type',
        ),
        migrations.AddField(
            model_name='media',
            name='date_exact',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialib.creator'),
        ),
        migrations.AddField(
            model_name='media',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medialib.license'),
        ),
        migrations.AddField(
            model_name='media',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medialib.mediasource'),
        ),
    ]
