# Generated by Django 4.1.3 on 2022-12-15 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0022_auto_20221215_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='source_url',
        ),
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialib.mediasource'),
        ),
    ]
