# Generated by Django 4.1.3 on 2022-12-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0024_license_display_alter_mediasource_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
    ]
