# Generated by Django 4.1.4 on 2022-12-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0025_alter_media_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ('platform', 'name')},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('-upload_time',)},
        ),
        migrations.AlterModelOptions(
            name='mediasource',
            options={'ordering': ('-upload_time',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AddConstraint(
            model_name='creator',
            constraint=models.UniqueConstraint(fields=('platform', 'name'), name='unique_platform_name'),
        ),
    ]
