# Generated by Django 4.1.4 on 2023-01-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0026_alter_creator_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='display',
            new_name='public',
        ),
    ]
