# Generated by Django 4.1.4 on 2023-01-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0027_rename_display_media_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediasource',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
