# Generated by Django 4.1.4 on 2023-01-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0030_creatorwebsite_alter_creator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorwebsite',
            name='platform',
            field=models.CharField(blank=True, choices=[('TW', 'Twitter'), ('YT', 'YouTube'), ('IG', 'Instagram')], max_length=2),
        ),
    ]
