# Generated by Django 4.1.4 on 2023-02-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0033_auto_20230130_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemedia',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=400, verbose_name='URL'),
        ),
    ]
