# Generated by Django 4.1.4 on 2023-02-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0034_filemedia_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
