# Generated by Django 4.1.6 on 2023-02-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0035_creator_official'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ('-official', 'name')},
        ),
        migrations.AlterModelOptions(
            name='filemedia',
            options={'ordering': ('-date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'YouTube video'},
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='YouTube ID'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
