# Generated by Django 4.1.6 on 2023-02-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0036_alter_creator_options_alter_filemedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
