# Generated by Django 4.1.6 on 2023-02-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0037_tag_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('category', 'name')},
        ),
    ]
