# Generated by Django 4.1.6 on 2023-03-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0038_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='embeddable',
            field=models.BooleanField(default=True),
        ),
    ]
