# Generated by Django 4.1.6 on 2023-03-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0039_youtubevideo_embeddable'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=400, verbose_name='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='filemedia',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=400, verbose_name='Thumbnail URL'),
        ),
    ]
