# Generated by Django 4.2.2 on 2023-06-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0044_photo_height_photo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
