name: test-younha
run-name: Test Younha Library
on: [push, pull_request]

jobs:
  test-younha:
    runs-on: ubuntu-latest
    env:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: younha
      SQL_USER: younha
      SQL_PASSWORD: younha
      SQL_HOST: postgres
      SQL_PORT: 5432
      SECRET_KEY: younha

    services:
      postgres:
        image: postgres:13-bullseye
        env:
          POSTGRES_USER: younha
          POSTGRES_PASSWORD: younha
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run python manage.py test
