name: test-younha
run-name: Test Younha Library
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-younha:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    services:
      postgres:
        image: postgres:13-bullseye
        env:
          POSTGRES_USER: younha
          POSTGRES_PASSWORD: younha
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install
      - name: Create secrets.json
        working-directory: ..
        run: |
            mkdir conf
            echo '{"db_host": "localhost", ' > conf/secrets.json
            echo '"db_password": "younha", ' >> conf/secrets.json
            echo '"secret_key": "a"}' >> conf/secrets.json
      - name: Run tests
        run: poetry run python manage.py test
